name:                hsboot
version:             0.1.0.0
github:              "parsonsmatt/hsboot"
license:             BSD3
author:              "Matt Parsons"
maintainer:          "parsonsmatt@gmail.com"
copyright:           "Matt Parsons"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/parsonsmatt/hsboot#readme>

dependencies:
- base >= 4.7 && < 5
- aeson

library:
  source-dirs: src

executables:
  hsboot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsboot

tests:
  hsboot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsboot
